USE questionnaire_project;
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (1, 'Q1', 'Frequency of Plastic Bag Use', 'INTEGER', '(1-5)', 'A', 'PLASTIC USE');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (2, 'Q2', 'Frequency of Bottle Use', 'INTEGER', '(1-5)', 'A', 'PLASTIC USE');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (3, 'Q3', 'Frequency of Use of Plastic Cups/Straws/Cutlery', 'INTEGER', '(1-5)', 'A', 'PLASTIC USE');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (4, 'Q4', 'Main Place of Plastic Use', 'INTEGER', '(1-5)', 'A', 'PLASTIC USE');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (5, 'Q5', 'Use of Reusable Bag', 'INTEGER', '(1-5)', 'A', 'REUSABLE ALTERNATIVES');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (6, 'Q6', 'Bottle/Flask Use', 'INTEGER', '(1-5)', 'A', 'REUSABLE ALTERNATIVES');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (7, 'Q7', 'Use of Reusable Cup/Utensil', 'INTEGER', '(1-5)', 'A', 'REUSABLE ALTERNATIVES');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (8, 'Q8_1', 'Environmental Burden', 'INTEGER', '(1-5)', 'B', 'ENVIRONMENTAL ATTITUDES');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (9, 'Q8_2', 'Problem for The Local Community Of Grevena', 'INTEGER', '(1-5)', 'B', 'ENVIRONMENTAL ATTITUDES');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (10, 'Q8_3', 'Citizens Can Reduce Plastic Use', 'INTEGER', '(1-5)', 'B', 'ENVIRONMENTAL ATTITUDES');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (11, 'Q8_4', 'Level of Awareness About Impacts', 'INTEGER', '(1-5)', 'B', 'ENVIRONMENTAL ATTITUDES');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (12, 'Q9_1', 'Intention To Replace Plastic Bags', 'INTEGER', '(1-5)', 'B', 'BEHAVIORAL INTENTIONS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (13, 'Q9_2', 'Intention To Replace Plastic Bottles', 'INTEGER', '(1-5)', 'B', 'BEHAVIORAL INTENTIONS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (14, 'Q9_3', 'Intention To Use Reusable Utensils', 'INTEGER', '(1-5)', 'B', 'BEHAVIORAL INTENTIONS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (15, 'Q9_4', 'Intention To Reduce Overall Plastic Use', 'INTEGER', '(1-5)', 'B', 'BEHAVIORAL INTENTIONS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (16, 'Q10_1', 'Barrier: Cost', 'INTEGER', '(1-5)', 'B', 'BARRIERS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (17, 'Q10_2', 'Barrier: Habit/Convenience', 'INTEGER', '(1-5)', 'B', 'BARRIERS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (18, 'Q10_3', 'Barrier: Availability', 'INTEGER', '(1-5)', 'B', 'BARRIERS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (19, 'Q10_4', 'Barrier: Lack of Information', 'INTEGER', '(1-5)', 'B', 'BARRIERS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (20, 'Q11', 'Most Helpful Factor', 'INTEGER', '(1-5)', 'B', 'PERCEPTIONS AND OPINIONS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (21, 'Q12', 'Perceived Willingness of Grevena Residents', 'INTEGER', '(1-5)', 'B', 'PERCEPTIONS AND OPINIONS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (22, 'Q13', 'Information/Awareness Helps Reduce Plastic', 'INTEGER', '(1-5)', 'B', 'PERCEPTIONS AND OPINIONS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (23, 'Q14', 'Likelihood Of Recommendation', 'INTEGER', '(1-5)', 'B', 'PERCEPTIONS AND OPINIONS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (24, 'Q15', 'Gender', 'INTEGER', '(1-4)', 'C', 'DEMOGRAPHICS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (25, 'Q16', 'Age Group', 'INTEGER', '(1-6)', 'C', 'DEMOGRAPHICS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (26, 'Q17', 'Educational Level', 'INTEGER', '(1-6)', 'C', 'DEMOGRAPHICS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (27, 'Q18', 'Employment Status', 'INTEGER', '(1-8)', 'C', 'DEMOGRAPHICS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (28, 'Q19', 'Place of Residence', 'INTEGER', '(1-3)', 'C', 'DEMOGRAPHICS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (29, 'Q20', 'Household Size', 'INTEGER', '(1-4)', 'C', 'DEMOGRAPHICS');
INSERT INTO Questions(QuestionID, Question_Code, Question_Text, Question_Type, Valid_Values, Part, Group_Name) VALUES (30, 'Q21', 'Consent For Future Use of Responses', 'INTEGER', '(1-2)', 'C', 'CONSENT');
INSERT INTO Participants(ParticipantID) VALUES (1);
INSERT INTO Participants(ParticipantID) VALUES (2);
INSERT INTO Participants(ParticipantID) VALUES (3);
INSERT INTO Participants(ParticipantID) VALUES (4);
INSERT INTO Participants(ParticipantID) VALUES (5);
INSERT INTO Participants(ParticipantID) VALUES (6);
INSERT INTO Participants(ParticipantID) VALUES (7);
INSERT INTO Participants(ParticipantID) VALUES (8);
INSERT INTO Participants(ParticipantID) VALUES (9);
INSERT INTO Participants(ParticipantID) VALUES (10);
INSERT INTO Participants(ParticipantID) VALUES (11);
INSERT INTO Participants(ParticipantID) VALUES (12);
INSERT INTO Participants(ParticipantID) VALUES (13);
INSERT INTO Participants(ParticipantID) VALUES (14);
INSERT INTO Participants(ParticipantID) VALUES (15);
INSERT INTO Participants(ParticipantID) VALUES (16);
INSERT INTO Participants(ParticipantID) VALUES (17);
INSERT INTO Participants(ParticipantID) VALUES (18);
INSERT INTO Participants(ParticipantID) VALUES (19);
INSERT INTO Participants(ParticipantID) VALUES (20);