USE questionnaire_project;
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (1, 1, 1, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (2, 1, 2, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (3, 1, 3, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (4, 1, 4, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (5, 1, 5, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (6, 1, 6, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (7, 1, 7, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (8, 1, 8, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (9, 1, 9, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (10, 1, 10, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (11, 1, 11, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (12, 1, 12, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (13, 1, 13, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (14, 1, 14, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (15, 1, 15, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (16, 1, 16, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (17, 1, 17, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (18, 1, 18, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (19, 1, 19, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (20, 1, 20, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (21, 1, 21, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (22, 1, 22, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (23, 1, 23, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (24, 1, 24, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (25, 1, 25, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (26, 1, 26, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (27, 1, 27, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (28, 1, 28, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (29, 1, 29, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (30, 1, 30, 1); 
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (31, 2, 1, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (32, 2, 2, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (33, 2, 3, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (34, 2, 4, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (35, 2, 5, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (36, 2, 6, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (37, 2, 7, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (38, 2, 8, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (39, 2, 9, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (40, 2, 10, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (41, 2, 11, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (42, 2, 12, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (43, 2, 13, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (44, 2, 14, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (45, 2, 15, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (46, 2, 16, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (47, 2, 17, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (48, 2, 18, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (49, 2, 19, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (50, 2, 20, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (51, 2, 21, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (52, 2, 22, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (53, 2, 23, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (54, 2, 24, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (55, 2, 25, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (56, 2, 26, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (57, 2, 27, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (58, 2, 28, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (59, 2, 29, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (60, 2, 30, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (61, 3, 1, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (62, 3, 2, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (63, 3, 3, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (64, 3, 4, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (65, 3, 5, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (66, 3, 6, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (67, 3, 7, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (68, 3, 8, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (69, 3, 9, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (70, 3, 10, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (71, 3, 11, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (72, 3, 12, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (73, 3, 13, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (74, 3, 14, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (75, 3, 15, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (76, 3, 16, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (77, 3, 17, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (78, 3, 18, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (79, 3, 19, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (80, 3, 20, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (81, 3, 21, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (82, 3, 22, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (83, 3, 23, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (84, 3, 24, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (85, 3, 25, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (86, 3, 26, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (87, 3, 27, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (88, 3, 28, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (89, 3, 29, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (90, 3, 30, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (91, 4, 1, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (92, 4, 2, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (93, 4, 3, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (94, 4, 4, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (95, 4, 5, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (96, 4, 6, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (97, 4, 7, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (98, 4, 8, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (99, 4, 9, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (100, 4, 10, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (101, 4, 11, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (102, 4, 12, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (103, 4, 13, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (104, 4, 14, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (105, 4, 15, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (106, 4, 16, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (107, 4, 17, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (108, 4, 18, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (109, 4, 19, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (110, 4, 20, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (111, 4, 21, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (112, 4, 22, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (113, 4, 23, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (114, 4, 24, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (115, 4, 25, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (116, 4, 26, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (117, 4, 27, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (118, 4, 28, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (119, 4, 29, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (120, 4, 30, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (121, 5, 1, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (122, 5, 2, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (123, 5, 3, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (124, 5, 4, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (125, 5, 5, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (126, 5, 6, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (127, 5, 7, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (128, 5, 8, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (129, 5, 9, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (130, 5, 10, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (131, 5, 11, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (132, 5, 12, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (133, 5, 13, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (134, 5, 14, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (135, 5, 15, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (136, 5, 16, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (137, 5, 17, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (138, 5, 18, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (139, 5, 19, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (140, 5, 20, 99);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (141, 5, 21, 3);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (142, 5, 22, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (143, 5, 23, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (144, 5, 24, 2);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (145, 5, 25, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (146, 5, 26, 5);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (147, 5, 27, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (148, 5, 28, 1);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (149, 5, 29, 4);
INSERT INTO Responses(ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (150, 5, 30, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (151, 6, 1, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (152, 6, 2, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (153, 6, 3, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (154, 6, 4, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (155, 6, 5, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (156, 6, 6, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (157, 6, 7, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (158, 6, 8, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (159, 6, 9, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (160, 6, 10, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (161, 6, 11, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (162, 6, 12, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (163, 6, 13, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (164, 6, 14, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (165, 6, 15, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (166, 6, 16, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (167, 6, 17, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (168, 6, 18, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (169, 6, 19, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (170, 6, 20, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (171, 6, 21, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (172, 6, 22, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (173, 6, 23, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (174, 6, 24, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (175, 6, 25, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (176, 6, 26, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (177, 6, 27, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (178, 6, 28, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (179, 6, 29, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (180, 6, 30, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (181, 7, 1, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (182, 7, 2, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (183, 7, 3, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (184, 7, 4, 99);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (185, 7, 5, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (186, 7, 6, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (187, 7, 7, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (188, 7, 8, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (189, 7, 9, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (190, 7, 10, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (191, 7, 11, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (192, 7, 12, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (193, 7, 13, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (194, 7, 14, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (195, 7, 15, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (196, 7, 16, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (197, 7, 17, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (198, 7, 18, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (199, 7, 19, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (200, 7, 20, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (201, 7, 21, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (202, 7, 22, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (203, 7, 23, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (204, 7, 24, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (205, 7, 25, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (206, 7, 26, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (207, 7, 27, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (208, 7, 28, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (209, 7, 29, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (210, 7, 30, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (211, 8, 1, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (212, 8, 2, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (213, 8, 3, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (214, 8, 4, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (215, 8, 5, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (216, 8, 6, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (217, 8, 7, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (218, 8, 8, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (219, 8, 9, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (220, 8, 10, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (221, 8, 11, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (222, 8, 12, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (223, 8, 13, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (224, 8, 14, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (225, 8, 15, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (226, 8, 16, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (227, 8, 17, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (228, 8, 18, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (229, 8, 19, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (230, 8, 20, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (231, 8, 21, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (232, 8, 22, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (233, 8, 23, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (234, 8, 24, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (235, 8, 25, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (236, 8, 26, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (237, 8, 27, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (238, 8, 28, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (239, 8, 29, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (240, 8, 30, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (241, 9, 1, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (242, 9, 2, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (243, 9, 3, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (244, 9, 4, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (245, 9, 5, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (246, 9, 6, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (247, 9, 7, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (248, 9, 8, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (249, 9, 9, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (250, 9, 10, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (251, 9, 11, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (252, 9, 12, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (253, 9, 13, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (254, 9, 14, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (255, 9, 15, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (256, 9, 16, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (257, 9, 17, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (258, 9, 18, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (259, 9, 19, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (260, 9, 20, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (261, 9, 21, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (262, 9, 22, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (263, 9, 23, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (264, 9, 24, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (265, 9, 25, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (266, 9, 26, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (267, 9, 27, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (268, 9, 28, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (269, 9, 29, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (270, 9, 30, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (271, 10, 1, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (272, 10, 2, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (273, 10, 3, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (274, 10, 4, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (275, 10, 5, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (276, 10, 6, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (277, 10, 7, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (278, 10, 8, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (279, 10, 9, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (280, 10, 10, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (281, 10, 11, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (282, 10, 12, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (283, 10, 13, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (284, 10, 14, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (285, 10, 15, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (286, 10, 16, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (287, 10, 17, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (288, 10, 18, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (289, 10, 19, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (290, 10, 20, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (291, 10, 21, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (292, 10, 22, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (293, 10, 23, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (294, 10, 24, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (295, 10, 25, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (296, 10, 26, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (297, 10, 27, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (298, 10, 28, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (299, 10, 29, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (300, 10, 30, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (301, 11, 1, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (302, 11, 2, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (303, 11, 3, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (304, 11, 4, 99);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (305, 11, 5, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (306, 11, 6, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (307, 11, 7, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (308, 11, 8, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (309, 11, 9, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (310, 11, 10, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (311, 11, 11, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (312, 11, 12, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (313, 11, 13, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (314, 11, 14, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (315, 11, 15, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (316, 11, 16, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (317, 11, 17, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (318, 11, 18, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (319, 11, 19, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (320, 11, 20, 99);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (321, 11, 21, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (322, 11, 22, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (323, 11, 23, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (324, 11, 24, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (325, 11, 25, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (326, 11, 26, 6);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (327, 11, 27, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (328, 11, 28, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (329, 11, 29, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (330, 11, 30, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (331, 12, 1, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (332, 12, 2, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (333, 12, 3, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (334, 12, 4, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (335, 12, 5, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (336, 12, 6, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (337, 12, 7, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (338, 12, 8, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (339, 12, 9, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (340, 12, 10, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (341, 12, 11, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (342, 12, 12, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (343, 12, 13, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (344, 12, 14, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (345, 12, 15, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (346, 12, 16, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (347, 12, 17, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (348, 12, 18, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (349, 12, 19, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (350, 12, 20, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (351, 12, 21, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (352, 12, 22, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (353, 12, 23, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (354, 12, 24, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (355, 12, 25, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (356, 12, 26, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (357, 12, 27, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (358, 12, 28, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (359, 12, 29, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (360, 12, 30, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (361, 13, 1, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (362, 13, 2, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (363, 13, 3, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (364, 13, 4, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (365, 13, 5, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (366, 13, 6, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (367, 13, 7, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (368, 13, 8, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (369, 13, 9, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (370, 13, 10, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (371, 13, 11, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (372, 13, 12, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (373, 13, 13, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (374, 13, 14, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (375, 13, 15, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (376, 13, 16, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (377, 13, 17, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (378, 13, 18, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (379, 13, 19, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (380, 13, 20, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (381, 13, 21, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (382, 13, 22, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (383, 13, 23, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (384, 13, 24, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (385, 13, 25, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (386, 13, 26, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (387, 13, 27, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (388, 13, 28, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (389, 13, 29, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (390, 13, 30, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (391, 14, 1, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (392, 14, 2, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (393, 14, 3, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (394, 14, 4, 99);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (395, 14, 5, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (396, 14, 6, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (397, 14, 7, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (398, 14, 8, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (399, 14, 9, NULL);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (400, 14, 10, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (401, 14, 11, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (402, 14, 12, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (403, 14, 13, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (404, 14, 14, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (405, 14, 15, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (406, 14, 16, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (407, 14, 17, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (408, 14, 18, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (409, 14, 19, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (410, 14, 20, 99);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (411, 14, 21, NULL);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (412, 14, 22, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (413, 14, 23, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (414, 14, 24, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (415, 14, 25, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (416, 14, 26, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (417, 14, 27, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (418, 14, 28, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (419, 14, 29, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (420, 14, 30, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (421, 15, 1, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (422, 15, 2, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (423, 15, 3, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (424, 15, 4, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (425, 15, 5, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (426, 15, 6, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (427, 15, 7, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (428, 15, 8, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (429, 15, 9, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (430, 15, 10, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (431, 15, 11, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (432, 15, 12, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (433, 15, 13, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (434, 15, 14, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (435, 15, 15, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (436, 15, 16, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (437, 15, 17, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (438, 15, 18, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (439, 15, 19, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (440, 15, 20, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (441, 15, 21, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (442, 15, 22, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (443, 15, 23, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (444, 15, 24, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (445, 15, 25, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (446, 15, 26, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (447, 15, 27, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (448, 15, 28, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (449, 15, 29, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (450, 15, 30, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (451, 16, 1, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (452, 16, 2, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (453, 16, 3, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (454, 16, 4, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (455, 16, 5, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (456, 16, 6, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (457, 16, 7, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (458, 16, 8, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (459, 16, 9, NULL);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (460, 16, 10, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (461, 16, 11, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (462, 16, 12, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (463, 16, 13, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (464, 16, 14, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (465, 16, 15, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (466, 16, 16, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (467, 16, 17, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (468, 16, 18, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (469, 16, 19, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (470, 16, 20, 99);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (471, 16, 21, NULL);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (472, 16, 22, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (473, 16, 23, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (474, 16, 24, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (475, 16, 25, 6);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (476, 16, 26, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (477, 16, 27, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (478, 16, 28, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (479, 16, 29, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (480, 16, 30, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (481, 17, 1, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (482, 17, 2, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (483, 17, 3, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (484, 17, 4, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (485, 17, 5, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (486, 17, 6, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (487, 17, 7, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (488, 17, 8, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (489, 17, 9, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (490, 17, 10, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (491, 17, 11, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (492, 17, 12, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (493, 17, 13, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (494, 17, 14, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (495, 17, 15, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (496, 17, 16, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (497, 17, 17, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (498, 17, 18, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (499, 17, 19, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (500, 17, 20, 99);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (501, 17, 21, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (502, 17, 22, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (503, 17, 23, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (504, 17, 24, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (505, 17, 25, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (506, 17, 26, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (507, 17, 27, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (508, 17, 28, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (509, 17, 29, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (510, 17, 30, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (511, 18, 1, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (512, 18, 2, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (513, 18, 3, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (514, 18, 4, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (515, 18, 5, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (516, 18, 6, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (517, 18, 7, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (518, 18, 8, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (519, 18, 9, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (520, 18, 10, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (521, 18, 11, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (522, 18, 12, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (523, 18, 13, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (524, 18, 14, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (525, 18, 15, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (526, 18, 16, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (527, 18, 17, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (528, 18, 18, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (529, 18, 19, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (530, 18, 20, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (531, 18, 21, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (532, 18, 22, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (533, 18, 23, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (534, 18, 24, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (535, 18, 25, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (536, 18, 26, 6);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (537, 18, 27, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (538, 18, 28, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (539, 18, 29, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (540, 18, 30, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (541, 19, 1, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (542, 19, 2, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (543, 19, 3, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (544, 19, 4, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (545, 19, 5, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (546, 19, 6, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (547, 19, 7, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (548, 19, 8, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (549, 19, 9, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (550, 19, 10, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (551, 19, 11, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (552, 19, 12, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (553, 19, 13, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (554, 19, 14, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (555, 19, 15, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (556, 19, 16, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (557, 19, 17, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (558, 19, 18, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (559, 19, 19, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (560, 19, 20, 99);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (561, 19, 21, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (562, 19, 22, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (563, 19, 23, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (564, 19, 24, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (565, 19, 25, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (566, 19, 26, 6);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (567, 19, 27, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (568, 19, 28, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (569, 19, 29, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (570, 19, 30, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (571, 20, 1, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (572, 20, 2, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (573, 20, 3, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (574, 20, 4, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (575, 20, 5, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (576, 20, 6, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (577, 20, 7, 1);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (578, 20, 8, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (579, 20, 9, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (580, 20, 10, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (581, 20, 11, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (582, 20, 12, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (583, 20, 13, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (584, 20, 14, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (585, 20, 15, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (586, 20, 16, 5);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (587, 20, 17, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (588, 20, 18, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (589, 20, 19, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (590, 20, 20, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (591, 20, 21, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (592, 20, 22, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (593, 20, 23, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (594, 20, 24, 2);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (595, 20, 25, 6);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (596, 20, 26, 6);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (597, 20, 27, 6);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (598, 20, 28, 3);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (599, 20, 29, 4);
INSERT INTO Responses (ResponseID, ParticipantID, QuestionID, Answer_Value) VALUES (600, 20, 30, 1);